# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

### Site settings ###
title: 'Ubuntu 17.10 探索筆記'
email: samwhelp@users.noreply.github.com
description: > # this means to ignore newlines until "baseurl:"
  探索「Ubuntu 17.10 (Artful Aardvark)」筆記
baseurl: "/note-ubuntu-17.10" # the subpath of your site, e.g. /blog
url: "http://samwhelp.github.io" # the base hostname & protocol for your site
#twitter_username: jekyllrb
#github_username:  jekyll


### Permalink ###
permalink: '/read/article/:slug'


### Build settings ###
markdown: kramdown
